import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import ClientBody from "./ClientBody";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body suppressHydrationWarning className="antialiased">
        <ClientBody>
          <header className="flex justify-between items-center px-8 py-4 bg-white shadow-sm sticky top-0 z-30">
            <div className="flex items-center">
              <span className="text-[1.7rem] font-bold text-[#464fc3] mr-10">
                <Link href="/">Vick and Edit</Link>
              </span>
              <nav className="flex gap-8 text-[1rem] font-medium text-[#222]">
                <Link href="/">Home</Link>
                <Link href="/projects">Projects</Link>
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </ClientBody>
      </body>
    </html>
  );
}
